// Vue/App.vue
<template>
    <div>
        <Typewriter :messages="messages" :pause="10" :typingSpeed="50" :cursorDelay="200" cursorSymbol="|" />
    </div>
</template>

<script setup lang="ts">

import Typewriter from './Typewriter.vue';

const messages = [
    'Typewriter :)',
    'hello',
    'this is a message :)',
    '...and another message!',
];

</script>

// App/src/App.tsx
import Typewriter from './Typewriter';

const App = () => {

  const messages = [
    'Typewriter :)',
    'hello',
    'this is a message :)',
    '...and another message!',
  ];

  return (
    <div>
      <Typewriter
        messages={messages}
        pause={10}
        typingSpeed={50}
        cursorDelay={200}
        cursorSymbol="|"
      />
    </div>
  );
};

export default App;
